apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-katzstunnel-rprojects
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 49Gi
